
[window]
opacity = 0.90

[window.padding]
x = 8
y = 6

[font]
size = 9

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[cursor.style]
blinking = "Off"
shape = "Block"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/bin/bash"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[colors.normal]
black   = "0x21222c"
red     = "0xff5555"
green   = "0x50fa7b"
yellow  = "0xf1fa8c"
blue    = "0xbd93f9"
magenta = "0xff79c6"
cyan    = "0x8be9fd"
white   = "0xf8f8f2"

[colors.bright]
black   = "0x6272a4"
red     = "0xff6e6e"
green   = "0x69ff94"
yellow  = "0xffffa5"
blue    = "0xd6acff"
magenta = "0xff92df"
cyan    = "0xa4ffff"
white   = "0xffffff"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[terminal]
